name: Update snode cache

on:
    workflow_dispatch: # Manual trigger
    schedule:
        - cron: "0 0 * * 0" # Weekly on Sunday (optional)
permissions:
    contents: write
    pull-requests: write

jobs:
    update-snode-cache:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"

            - name: Install Yarn globally
              run: npm install -g yarn

            - name: Initialize package.json if needed
              run: |
                  if [ ! -f package.json ]; then
                    yarn init --yes
                  fi

            - name: Install dependencies
              run: |
                  yarn add -D zod node-fetch

            - name: Run script
              run: npx -y tsx populate_cache.ts

            - name: remove package.json
              run: rm -f package.json yarn.lock

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "chore: add script dependencies and update cache"
                  branch: update-cache
                  delete-branch: true
                  title: "chore: Update dependencies and regenerate cache"
                  body: |
                      ## Changes
                      - Regenerated cache data by running `populate_cache.ts`

                      Auto-generated by workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
